apiVersion: v1
kind: Service
metadata:
  name: plex-ingress
  namespace: default
spec:
  ports:
    - name: plex-ingress
      port: 32400
      targetPort: 32400
      protocol: TCP
  type: ClusterIP
  ClusterIP: None
  # externalTrafficPolicy: Local
---
kind: Endpoints
apiVersion: v1
metadata:
  name: plex-ingress
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.1.150
    ports:
      - name: plex-ingress
        port: 32400
        protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
    hajimari.io/enable: "true"
    hajimari.io/group: Media
    nginx.ingress.kubernetes.io/app-root: /web

spec:
  rules:
    - host: plex.${SECRET_DOMAIN}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: plex-ingress
                port:
                  number: 32400

  tls:
    - hosts:
        - plex.${SECRET_DOMAIN}
      secretName: plex-tls
  ingressClassName: nginx
