---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: default
spec:
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 6h
  values:
    image:
      repository: ghcr.io/linuxserver/bazarr
      tag: development-version-v1.2.2-beta.21
      pullPolicy: IfNotPresent
    global:
      fullnameOverride: bazarr
    env:
      TZ: America/Chicago
      PUID: 568
      PGID: 568
    service:
      main:
        ports:
          http:
            port: 6767
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          hajimari.io/enable: "true"
          hajimari.io/group: Media
          hajimari.io/icon: mdi:subtitles
        hosts:
          - host: bazarr.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - bazarr.${SECRET_DOMAIN}
            secretName: bazarr-tls
    persistence:
      config:
        enabled: true
        mountPath: /config
        storageClass: local-path
      vids:
        enabled: true
        mountPath: /data
        accessMode: ReadWriteMany
        existingClaim: media-pvc-ssd
        storageClass: "nfs-client-ssd"
