---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tubearchivist
  namespace: default
spec:
  chart:
    spec:
      chart: tubearchivist
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: stiforr
        namespace: flux-system
  interval: 6h0m0s
  install:
    remediation:
      retries: 30
  upgrade:
    remediation:
      retries: 30
  values:
    image:
      repository: bbilly1/tubearchivist
      tag: v0.4.5
    env:
      TA_HOST: "tubearchivist.${SECRET_DOMAIN}"
      TA_PASSWORD: "changeme"
      TA_USERNAME: "admin"
      ES_URL: "http://tubearchivist-elasticsearch:9200"
      ELASTIC_PASSWORD: "changeme"
      REDIS_HOST: "tubearchivist-redis-master"
    redis:
      master:
        persistence:
          storageClass: nfs-client-ssd
    elasticsearch:
      image:
        repository: bitnami/elasticsearch
        tag: 8.6.0
      master:
        persistence:
          storageClass: nfs-client-ssd
      extraConfig:
        path:
          repo: /usr/share/elasticsearch/data/snapshot

    persistence:
      youtube:
        enabled: true
        existingClaim: media-pvc-ssd
        subPath: youtube
      config:
        enabled: false
        storageClass: nfs-client-ssd
      cache:
        storageClass: nfs-client-ssd
        accessMode: ReadWriteMany
        size: 20Gi
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/group: Media
          hajimari.io/icon: mdi:youtube
        hosts:
          - host: &host tubearchivist.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: tubearchivist-tls
    service:
      main:
        ports:
          http:
            port: 8000
