---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Chicago"
  METALLB_LB_RANGE: "192.168.1.100-192.168.1.110"
  METALLB_K8S_GATEWAY_ADDR: "192.168.1.101"
  METALLB_INGRESS_ADDR: "192.168.1.102"
  KUBE_VIP_ADDR: "192.168.1.155"
  CLUSTER_CIDR: "10.42.0.0/16"
  SERVICE_CIDR: "10.43.0.0/16"
